### PR TITLE
feat: add cli entry point

### PR DESCRIPTION
**Pull request by alegay-adeo**
I made a CLI in order to use this tool in a CI just like prettier.

I also took the liberty to reformat the README a little and added the CLI example.

### CODE REVIEW

**Comment by szikszail** [comment]
Hi @alegay-adeo,
Is this a feature/tool you'd need, or you'd like to release yourself?
I see some benefit in having such a tool, but I'd make it a separate one in the **GherKing** family, e.g: `gherkin-formatter-cli`. We would welcome your contribution there.
This implementation introduces a dependency loop, unfortunately.

**Comment by alegay-adeo** [comment]
Hi !
Sorry for closing the PR, I didn't know if you were still maintaining the project.

I talked with my team and we thought it'd be a good idea to integrate a gherkin formatter for our feature files in our CI process, but we need it to be executable as a CLI so that's why.

What dependency loop did you detect ?

**Comment by szikszail** [comment]
Hi,

We are, just the pace and effort we can spend here is limited. But this package and some others are up-to-date and soon the new version of gherking and the precompilers will be released.

If you and your team would need such CLI tool, I think that would be the best to create one under the umbrella of GherKing, let's call it gherkin-formatter-cli, using the patterns we already use in the gherking CLI tool.

This would also allow us to avoid the dependency loop, i.e. gherkin-formatter --> gherkin-io --> gherkin-formatter --> ...

What do you think? 

If you or your team would like to contribute, we would be happy to work with you on this.

**Comment by alegay-adeo** [comment]
Hi ! I just came here to see that my answer had never been sent. Sorry.

I'd be happy to contribute as it would be a good addition to our workflow as well. How do you want me to proceed for the new package ?
Do you init the repo/project on your side ?

**Comment by szikszail** [comment]
@alegay-adeo  cool. Yes, I'll create the repo and a template code and let you know about the next steps.

**Comment by szikszail** [comment]
@alegay-adeo I just sent an invite to you to our team, please accept it, then you'll be able to implement the CLI in this repo: https://github.com/gherking/gherkin-formatter-cli

This is a similar CLI than GherKing is, but without the precompiled part. In this state, you only need to adjust it to the new name (see TODO section in README.md) and implement any additional logic to support the formatting options of `gherkin-formatter`.

I'll create an issue as well and assign it to you as soon as you accepted the invite.

**Pull request closed without merging**
